// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Session/direct connection for migrations; app runtime uses DATABASE_URL in lib/db.ts
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
